#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// Copyright (C) 2025-2026 Polycode Limited
// scripts/build-web.cjs
// Usage: node .github/agentic-lib/scripts/build-web.cjs
//
// Builds the docs/ directory for web serving:
// 1. Creates docs/ and copies src/web/* into it
// 2. Generates docs/lib.js — a self-contained browser module with:
//    - Package identity (name, version, description) from package.json
//    - Browser-safe exported functions extracted from src/lib/main.js
//    This overwrites the src/web/lib.js re-export (which only works in dev).
//
// This file is part of the Example Suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
// This file is licensed under the MIT License. For details, see LICENSE-MIT

const fs = require("fs");
const path = require("path");

const docsDir = path.resolve("docs");

// Step 1: Create docs/ and copy src/web/* if it exists
fs.mkdirSync(docsDir, { recursive: true });
fs.writeFileSync(path.join(docsDir, ".nojekyll"), "");

const webDir = path.resolve("src", "web");
if (fs.existsSync(webDir)) {
  for (const entry of fs.readdirSync(webDir, { withFileTypes: true })) {
    const src = path.join(webDir, entry.name);
    const dest = path.join(docsDir, entry.name);
    if (entry.isFile()) {
      fs.copyFileSync(src, dest);
    } else if (entry.isDirectory()) {
      fs.cpSync(src, dest, { recursive: true });
    }
  }
}

// Step 2: Generate docs/lib.js — self-contained browser module
// This overwrites the re-export copied from src/web/lib.js above,
// replacing it with a standalone module that works on GitHub Pages
// (where src/lib/main.js and package.json are not available).
const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
const sections = [];

// Identity exports from package.json
sections.push(
  `export const name = ${JSON.stringify(pkg.name)};`,
  `export const version = ${JSON.stringify(pkg.version)};`,
  `export const description = ${JSON.stringify(pkg.description)};`,
  "",
  "export function getIdentity() {",
  "  return { name, version, description };",
  "}"
);

// Extract browser-safe exported functions from src/lib/main.js
const mainPath = path.resolve("src", "lib", "main.js");
if (fs.existsSync(mainPath)) {
  const mainSrc = fs.readFileSync(mainPath, "utf8");
  const lines = mainSrc.split("\n");

  // Skip identity-related exports and the main/CLI function — only extract
  // mission-specific exported functions (e.g. hammingDistance, etc.)
  const SKIP_FUNCTIONS = new Set(["getIdentity", "main"]);

  for (let i = 0; i < lines.length; i++) {
    const fnMatch = lines[i].match(/^export\s+(async\s+)?function\s+(\w+)/);
    if (fnMatch && !SKIP_FUNCTIONS.has(fnMatch[2])) {
      // Collect the full function body by tracking brace depth
      const fnLines = [lines[i]];
      let braceDepth = 0;
      for (let j = i; j < lines.length; j++) {
        for (const ch of lines[j]) {
          if (ch === "{") braceDepth++;
          if (ch === "}") braceDepth--;
        }
        if (j > i) fnLines.push(lines[j]);
        if (braceDepth === 0 && j >= i) {
          break;
        }
      }
      sections.push("");
      sections.push(fnLines.join("\n"));
    }
  }
}

const header = [
  "// docs/lib.js",
  "// Self-contained browser module generated by build-web.cjs.",
  "// Identity from package.json; functions extracted from src/lib/main.js.",
  "// Do not edit — regenerate with: npm run build:web",
  "",
].join("\n");

fs.writeFileSync(path.join(docsDir, "lib.js"), header + sections.join("\n") + "\n");
console.log("Wrote docs/lib.js");
